server:
  port: 80

spring:
  application:
    name: order-fegin-hystrix-consumer-80
eureka:
  client:
    service-url:
      register-with-eureka: false
      defaultZone: http://eureka7001.com:7001/eureka,
ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间 这两个属性报错原因，idea没有提示
  ReadTimeout: 5000
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ConnectTimeout: 5000
feign:
  hystrix:
    enabled: true
