#8004表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 80


#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: consul-consumer-payment
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        #hostname: 127.0.0.1


